name: Output Action
description: simulates output for a custom action

outputs:
  custom_action_output:
    description: "just trying custom action's output"
    value: ${{ steps.output_test.outputs.custom_action_output}}

  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}

runs:
  using: "composite"
  steps:
    - name: Output Test
      id: output_test
      shell: bash
      run:
        CUSTOM_OP="CUSTOM ACTION RULEZ"
        echo "custom_action_output=$(echo $CUSTOM_OP)" >> $GITHUB_OUTPUT
    
    - id: random-number-generator
      run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      shell: bash

    - name: Another random number
      id: another_random
      shell: bash
      run:
        echo "another_random=$(echo $RANDOM)" >> $GTIHUB_OUTPUT

    - name: Showing another random number
      shell: bash
      run:
        echo ${{ steps.another_random.outputs.another_random }}
