name: Conditional Action
description: test conditions

runs:
  using: "composite"
  steps:
    - name: Init
      shell: bash
      run: echo "Initializing ..."

    - name: First Cond
      shell: bash
      if: ${{ github.job == 'envjob1' }}
      run:
        echo "This is job1"
        echo ${{ github.job }}

    - name: Second Cond
      shell: bash
      if: ${{ github.job == 'envjob2' }}
      run:
        echo "This is job 2"

    - name: Third Cond
      shell: bash
      if: ${{ github.job == 'envjob2' }} || ${{ github.job == 'envjob1' }}
      run: |
        echo "Run anytime"