name: First Custom Action
description: Just giving a try

runs:
  using: "composite"
  steps:
    - name: Init
      shell: bash
      run: |
        echo "This is first custom action"
    
    - name: And Action
      run:
        echo "And that's it from my custom action"
