name: First Custom Action
description: Just giving a try

inputs:
  custom_param:
    description: trying inputs for custom actions
    required: true

  mu:
    description: input strategy from the job
    required: true

  sigma:
    description: input strategy from the job
    required: true

runs:
  using: "composite"
  steps:
    - name: Init
      shell: bash
      run: |
        echo "This is first custom action"
    
    - name: Parameter action
      shell: bash
      env:
        custom_param: ${{ inputs.custom_param }}
      run:
        echo "showing input parameter $custom_param"

    - name: Check Env Vars
      shell: bash
      run:
        echo "Env Var input from workflow $MYENVVAR"

    - name: Strategy check
      shell: bash
      run:
        echo "Matrix MU ${{ inputs.mu }}"
        echo "Matrix sigma ${{ inputs.sigma }}"

    - name: Check step vars
      id: step_var
      shell: bash
      run:
        echo "params_multiplication='${{ inputs.mu }} * ${{ inputs.sigma }}'" >> $GITHUB_OUTPUT

    - name: Check steps var 2
      shell: bash
      run:
        echo ${{ steps.step_var.outputs.params_multiplication }}

    - name: And Action
      shell: bash
      run:
        echo "And that's it from my custom action"

branding:
  icon: 'check'
  color: 'blue'