name: First Custom Action
description: Just giving a try

inputs:
  custom_param:
    description: trying inputs for custom actions
    required: true

  job_strategy:
    description: input strategy from the job
    required: true

runs:
  using: "composite"
  steps:
    - name: Init
      shell: bash
      run: |
        echo "This is first custom action"
    
    - name: Parameter action
      shell: bash
      env:
        custom_param: ${{ inputs.custom_param }}
      run:
        echo "showing input parameter $custom_param"

    - name: Check Env Vars
      shell: bash
      run:
        echo "Env Var input from workflow $MYENVVAR"

    - name: Strategy check
      shell: bash
      run:
        echo "Matrix MU ${{ input.job_strategy.mu }}"
        echo "Matrix sigma ${{ input.job_strategy.sigma }}"

    - name: And Action
      shell: bash
      run:
        echo "And that's it from my custom action"

branding:
  icon: 'check'
  color: 'blue'