name: dbx_workflow

run-name: DBX-TEST

on:
#  pull_request:
#    branches: [ "main", "dev" ]

  workflow_dispatch:
      inputs:
        test:
          type: string
          required: false
          default: ""

jobs:
    my_job:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repo
            uses: actions/checkout@v4

          - name: Set up Python 3.9
            uses: actions/setup-python@v5
            with:
              python-version: "3.9"

          - name: Run ls
            run: |
              echo $(ls -tr)

          - name: Upload ENSEMBLE File to DBX
            uses: databricks/upload-dbfs-temp@v0
            id: upload_ensemble
            with:
              local-path: "./files/ENSEMBLE.json"
              databricks-host: "https://enverus-pr-ue1-dev.cloud.databricks.com"
              databricks-token: "dapi00bbf0783c5b0fb6f8a2faf4ba06ff87"

          - name: Sleep
            run: |
              sleep 300s
            shell: bash

          - name: Run Notebook
            uses: databricks/run-notebook@v0
            with:
              local-notebook-path: "./templates/ntb_test.py"
              databricks-host: "https://enverus-pr-ue1-dev.cloud.databricks.com"
              databricks-token: "dapi00bbf0783c5b0fb6f8a2faf4ba06ff87"
              existing-cluster-id: "0123-123947-f9w7986"
              notebook-params-json: >
                [
                  {
                    "key": "ensemble_file_path",
                    "value": "${{ steps.upload_ensemble.outputs.dbfs-file-path }}"
                  }
                ]