name: testing workflow

run-name: ${{ github.actor }} is calling

on:
  workflow_dispatch:
    inputs:
      nelf_id:
        required: false
        type: string
      wolf_id:
        required: false
        type: string

env:
  ENVPASS: aksljdlsd

jobs:
  main_job:
    strategy:
      matrix:
        include:
          - name: NELF
            id: ${{ inputs.nelf_id }}
          - name: WOLF
            id: ${{ inputs.wolf_id }}
            run_wf: ${{ inputs.wolf_id != '' }}

    uses: ./.github/workflows/test_reuse.yml
    with:
      name: ${{ matrix.name }}
      id: ${{ matrix.id }}
      ref: ${{ env.ENVPASS }}