name: Poetry Test

run-name: Poetry-Test

on:
  workflow_dispatch:

jobs:
  init_job:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Starting a test"

  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Poetry
        run: pip install poetry

      - name: Load cached dependencies
        id: cache-poetry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pypoetry
          key: poetry-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            poetry-${{ runner.os }}-

      - name: Install dependencies
        run: poetry install --no-interaction --no-root
        if: steps.cache-poetry.outputs.cache-hit != 'true'

      - name: Just Echo
        run: |
          echo "First Job Done"

    second_job:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.9'

        - name: Install Poetry
          run: pip install poetry

        - name: Load cached dependencies
          id: cache-poetry
          uses: actions/cache@v3
          with:
            path: |
              ~/.cache/pypoetry
            key: poetry-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
            restore-keys: |
              poetry-${{ runner.os }}-

        - name: Install dependencies
          run: poetry install --no-interaction --no-root
          if: steps.cache-poetry.outputs.cache-hit != 'true'

        - name: Just Echo
          run: |
            echo "Second Job Done"