name: Reusable Workflow

on:
  workflow_call:
    # Map the workflow outputs to job outputs
    outputs:
      job_environment:
        description: "The first output string"
        value: ${{ jobs.check-matrix-first.outputs.job_environment }}
    
    inputs:
      dbx-env:
        required: true
        type: string

env:
  PROD: "prodprod"
  DEV: "devdev"
  COSI: ""

jobs:
  setup-github-envs:
    runs-on: ubuntu-latest
    steps:
        - name: Setup Envs Prod
          if: ${{ inputs.dbx-env == 'prod' }}
          run: |
            echo "COSI=${{ env.PROD }}" >> $GITHUB_ENV
            echo "RUN_ENV=environment_prod" >> $GITHUB_ENV
          shell: bash

        - name: Setup Envs Dev
          if: ${{ inputs.dbx-env == 'dev' }}
          run: |
            echo "COSI=${{ env.DEV }}" >> $GITHUB_ENV
            echo "RUN_ENV='environment_dev'"
          shell: bash

        - name: Sleep
          run:
            sleep 60

        - name: Print Github Envs
          run: |
            echo ${{ env.COSI }}
            echo ${{ env.RUN_ENV }}

  check-matrix-first:
    runs-on: ubuntu-latest

    needs: [ setup-github-envs ]

    outputs:
        job_environment: ${{ steps.check-env-vars.outputs.job-env }}
      
    env:
      MYHOST: ${{ inputs.host }}
      MYTOKEN: ${{ inputs.token }}
     
    steps:
      - name: Check Env Vars
        id: check-env-vars
        run: |
          echo "HOST is ${{ env.MYHOST }}"
          echo "TOKEN is ${{ env.MYTOKEN }}"
          echo "job-env=${{ env.MYHOST }}" >> $GITHUB_OUTPUT

      - name: easy echo
        run: |
          echo ${{ env.COSI }}