name: scripting workflow

run-name: ${{ github.actor }} is calling

on:
    pull_request:
      branches: [ "main" ]

    workflow_dispatch:
        inputs:
            script_path:
                type: string
                required: true

jobs:
    # find_script:
    #     runs-on: ubuntu-latest

    #     steps:
    #         - name:

    build:
        runs-on: ubuntu-latest

        if: ${{ github.event_name != 'workflow_dispatch' }}

        outputs:
            notebooks: ${{ steps.get_chenged_files.outputs.ntbs }}
            change_exists: ${{ steps.get_chenged_files.outputs.change_exists }}

        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Check Diff
              run: |
                git fetch origin main
                echo $(git diff origin/main)

            - name: Get changed files
              id: get_chenged_files
              run: |
                modified_files=$(git diff --name-only  --diff-filter=ACMR origin/main..HEAD -- ./scripts \
                | grep \.py | \
                sort -u )

                if [[ -z $modified_files ]]; then
                    echo "change_exists=false" >> $GITHUB_OUTPUT
                else
                    echo "change_exists=true" >> $GITHUB_OUTPUT
                fi

                echo "ntbs=${modified_files}" >> $GITHUB_OUTPUT

            - name: Check Output
              id: check_output
              run: |
                echo "Cechking output ..."
                echo ${{ steps.get_chenged_files.outputs.ntbs }}

    build_dispatch:
        runs-on: ubuntu-latest

        if: ${{ github.event_name == 'workflow_dispatch' }}

        outputs:
            notebooks: ${{ steps.get_output.outputs.ntbs }}

        steps:
            - name: Get Output
              id: get_output
              run: |
                echo "ntbs=\"${{ inputs.script_path }}\"" >> $GITHUB_OUTPUT

            - name: Check Output
              id: check_output
              run: |
                echo ${{ steps.get_output.outputs.ntbs }}

    unify_outputs:
        runs-on: ubuntu-latest
        needs: [ build, build_dispatch ]

        if: ${{ always() }}

        outputs:
            notebooks_json: ${{ steps.output_json.outputs.notebooks }}

        steps:
            - name: PR Output
              if: ${{ github.event_name == 'pull_request' }}
              run: |
                echo "notebooks_env=${{ needs.build.outputs.notebooks }}" >> $GITHUB_ENV

            - name: Dispatch Output
              if: ${{ github.event_name == 'workflow_dispatch' }}
              run: |
                echo "notebooks_env=${{ needs.build_dispatch.outputs.notebooks }}" >> $GITHUB_ENV

            - name: Unify Output
              id: unify_output
              run: |
                echo "${{ env.notebooks_env }}"
                packages=`echo "${{ env.notebooks_env }}" | while IFS= read -r n; do echo "\"$n\""; done`
                ntbs_list=`echo "${packages}" | tr '\n' ','`

                echo "Checking ..."
                echo "${ntbs_list}"

                echo "notebooks=${ntbs_list}" >> $GITHUB_OUTPUT

            - name: Check Output
              id: check_output
              run: |
                echo ${{ steps.unify_output.outputs.notebooks }}

            - name: Check Json
              run: |
                echo "Checking json ..."
                echo ${{ fromJson( steps.unify_output.outputs.notebooks ) }}

    deploy:
        runs-on: ubuntu-latest

        needs: [ unify_outputs ]

        if: ${{ always() && (github.event_name == 'asd') }}

        strategy:
            matrix:
              ntb: ${{ needs.unify_outputs.outputs.notebooks_json }}

        steps:
            - name: Checkout repo
              uses: actions/checkout@v3
    
            - name: Set up Python 3.9
              uses: actions/setup-python@v2
              with:
                python-version: "3.9"
        
            - name: Run Changed Scripts
              id: run_scripts
              run: |
                python ${{ matrix.ntb }}
