name: calling a workflow

run-name: ${{ github.actor }} is calling

on:
    workflow_dispatch:
        inputs:
            name:
                default: "John Doe"
                required: true
                type: string

            place:
                required: false
                type: choice
                options:
                  - "New York"
                  - "Old York"
                  - "ZOO York"
                  - "All"

jobs:
    init_j:
        runs-on: ubuntu-latest

        steps:
          - name: Just Init
            run: |
                echo "Initilialization ..."

    prepare_input:
      runs-on: ubuntu-latest

      outputs:
        matrix_input: ${{ steps.prepare_input.outputs.prepared_matrix }}

      steps:
        - name: Prepared Input
          id: prepare_input
          run: |
            if [[ "${{ inputs.place }}" != "All" ]]
            then 
              echo "prepared_matrix={\"include\":[{\"place\": ${{ inputs.place }} }]}" >> $GITHUB_OUTPUT
            else
              echo "prepared_matrix={\"include\":[{\"place\": \"New York\"},{\"place\": \"Old York\"},{\"place\": \"ZOO York\"}]}" >> $GITHUB_OUTPUT
            fi


    work_with_input:
        runs-on: ubuntu-latest
        needs: [ init_j, prepare_input ]

        strategy:
          matrix: ${{ fromJSON(needs.prepare_input.outputs.matrix_input) }}

        steps:
          - name: Checkout Repo
            uses: actions/checkout@v3

          - name: Setup Python
            uses: actions/setup-python@v4
            with:
                python-version: 3.9

          - name: Run Python Script
            run: |
                python ./scripts/greetings.py --name '${{ inputs.name }}' --place '${{ matrix.place }}'
