name: Reusable Test

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      id:
        required: true
        type: string
      run_wf:
        required: false
        type: boolean
        default: true

jobs:
  main_job:
    if: ${{ inputs.run_wf }}
    runs-on: ubuntu-latest
    steps:
      - name: test_matrix
        run: |
          echo "bool: ${{ inputs.run_wf }}"
          echo "Name: ${{ inputs.name }}"
          echo "ID: ${{ inputs.id }}"
          echo "Finish step"