name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    outputs:
        python_test: ${{steps.check_path.outputs.my_path}}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout  
        uses: actions/checkout@v3
      - name: Node Setup
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v

      - name: Check Path
        id: check_path
        run:
            echo "my_path=$PATH" >> $GITHUB_OUTPUT

    
      - name: Final Echo
        run: echo "That's it"

  python-stuff:
    runs-on: ubuntu-latest
    needs: [check-bats-version]
    steps:
      - name: Echoing
        run:
            echo "Starting with python stuff"

      - name: Checkout  
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
            python-version: 3.9

      - name: Install poetry
        run: 
            pip install poetry

      - name: Poetry version
        run:
            echo $(poetry --version)

      - name: Check previous job path
        run:
            echo ${{ needs.check-bats-version.outputs.python_test}}
            
      - name: Run an easy python script
        run:
            python my_script.py

      - name:
        run:
            echo "Finish with python stuff"
